name: workflow-practice

on:
  push:
    branches: [main]

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run flake8
        run: flake8 .