events {}

http {
    server {
        listen 80;

        location /api {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
        }

        location /health {
            return 200 "nginx healthy\n";
        }
    }
}